gdtoa/hexnan.o: gdtoa/hexnan.c \
  /home/mblasz/mimiker-sched0/lib/libc/gdtoa/gdtoaimp.h \
  /home/mblasz/mimiker-sched0/include/assert.h \
  /home/mblasz/mimiker-sched0/include/sys/cdefs.h \
  /home/mblasz/mimiker-sched0/include/stdint.h \
  /home/mblasz/mimiker-sched0/include/machine/int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/machine/int_const.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_const.h \
  /home/mblasz/mimiker-sched0/lib/libc/gdtoa/gdtoa.h \
  /home/mblasz/mimiker-sched0/lib/libc/gdtoa/arith.h \
  /home/mblasz/mimiker-sched0/include/sys/endian.h \
  /home/mblasz/mimiker-sched0/include/stddef.h \
  /home/mblasz/mimiker-sched0/lib/libc/gdtoa/gd_qnan.h \
  /home/mblasz/mimiker-sched0/include/stdio.h \
  /home/mblasz/mimiker-sched0/include/sys/types.h \
  /home/mblasz/mimiker-sched0/include/endian.h \
  /home/mblasz/mimiker-sched0/include/machine/types.h \
  /home/mblasz/mimiker-sched0/include/_locale.h \
  /home/mblasz/mimiker-sched0/include/stdlib.h \
  /home/mblasz/mimiker-sched0/include/string.h \
  /home/mblasz/mimiker-sched0/include/strings.h \
  /home/mblasz/mimiker-sched0/include/errno.h \
  /home/mblasz/mimiker-sched0/include/sys/errno.h \
  /home/mblasz/mimiker-sched0/include/float.h \
  /home/mblasz/mimiker-sched0/include/math.h
