strcspn.o: /home/mblasz/mimiker-sched0/lib/libc/string/strcspn.c \
  /home/mblasz/mimiker-sched0/include/sys/libkern.h \
  /home/mblasz/mimiker-sched0/include/sys/types.h \
  /home/mblasz/mimiker-sched0/include/sys/cdefs.h \
  /home/mblasz/mimiker-sched0/include/endian.h \
  /home/mblasz/mimiker-sched0/include/sys/endian.h \
  /home/mblasz/mimiker-sched0/include/stddef.h \
  /home/mblasz/mimiker-sched0/include/stdint.h \
  /home/mblasz/mimiker-sched0/include/machine/int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/machine/int_const.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_const.h \
  /home/mblasz/mimiker-sched0/include/machine/types.h \
  /home/mblasz/mimiker-sched0/include/stdarg.h \
  /home/mblasz/mimiker-sched0/include/limits.h \
  /home/mblasz/mimiker-sched0/include/sys/syslimits.h \
  /home/mblasz/mimiker-sched0/include/machine/limits.h \
  /home/mblasz/mimiker-sched0/include/_limits.h
