builtins/cmpdi2.o: builtins/cmpdi2.c \
  /home/mblasz/mimiker-sched0/lib/libc/builtins/int_lib.h \
  /home/mblasz/mimiker-sched0/include/float.h \
  /home/mblasz/mimiker-sched0/include/limits.h \
  /home/mblasz/mimiker-sched0/include/sys/syslimits.h \
  /home/mblasz/mimiker-sched0/include/machine/limits.h \
  /home/mblasz/mimiker-sched0/include/_limits.h \
  /home/mblasz/mimiker-sched0/include/stdbool.h \
  /home/mblasz/mimiker-sched0/include/stdint.h \
  /home/mblasz/mimiker-sched0/include/machine/int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/machine/int_const.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_const.h \
  /home/mblasz/mimiker-sched0/lib/libc/builtins/int_types.h \
  /home/mblasz/mimiker-sched0/lib/libc/builtins/int_endianness.h \
  /home/mblasz/mimiker-sched0/lib/libc/builtins/int_util.h
