# vim: tabstop=8 shiftwidth=8 noexpandtab:

TOPDIR	 = $(realpath $(dir $(filter %Makefile.common, $(MAKEFILE_LIST))))
SYSROOT  = $(TOPDIR)/sysroot
CACHEDIR = $(TOPDIR)/cache
DIR = $(patsubst $(TOPDIR)/%,%,$(CURDIR)/)

include $(TOPDIR)/build/toolchain.mk
include $(TOPDIR)/build/tools.mk
include $(TOPDIR)/build/flags.mk
include $(TOPDIR)/build/recipe.mk
include $(TOPDIR)/build/compile.mk
include $(TOPDIR)/build/common.mk
