#!/usr/bin/python3

import datetime
import pexpect
import time


def parseTime(child):
    match = str(child.match.group(1), 'utf-8')
    try:
        tm_time = time.strptime(match, "%H:%M:%S")
    except ValueError:
        return None
    return datetime.datetime(*(tm_time[0:6]))

child = pexpect.spawn('./launch', ['-t', 'rtc.elf'])
pattern = "Time is ([0-9]{2}:[0-9]{2}:[0-9]{2})"
assert(child.expect([pexpect.EOF, pattern], timeout=5))
# throw away first result – why?
assert(child.expect([pexpect.EOF, pattern], timeout=5))
t1 = parseTime(child)
assert(child.expect([pexpect.EOF, pattern], timeout=5))
t2 = parseTime(child)
assert(t2 - t1 == datetime.timedelta(seconds=1))
