# vim: tabstop=8 shiftwidth=8 noexpandtab:

TOPDIR = $(realpath ../..)

SOURCES = \
	atkbdc.c \
	hidkbd.c \
	hidm.c \
	ns16550.c \
	rtc.c \
	rtl8139.c \
	pit.c \
	stdvga.c \
	uhci.c \
	umass.c \
	usb.c

include $(TOPDIR)/build/build.kern.mk
