#include <riscv/asm.h>

ENTRY(copyinstr)
	# Not implemented!
	j .
END(copyinstr)

ENTRY(copyin)
	# Not implemented!
	j .
END(copyin)

ENTRY(copyout)
	# Not implemented!
	j .
END(copyout)

ENTRY(copyerr)
	# Not implemented!
	j .
END(copyerr)

ENTRY(try_load_word)
	# Not implemented!
	j .
END(try_load_word)

ENTRY(try_store_word)
	# Not implemented!
	j .
END(try_store_word)

ENTRY(fault)
	# Not implemented!
	j .
END(fault)

# vim: sw=8 ts=8 et
