stdio/fclose.o: stdio/fclose.c \
  /home/mblasz/mimiker-sched0/include/sys/cdefs.h \
  /home/mblasz/mimiker-sched0/include/assert.h \
  /home/mblasz/mimiker-sched0/include/errno.h \
  /home/mblasz/mimiker-sched0/include/sys/errno.h \
  /home/mblasz/mimiker-sched0/include/stdio.h \
  /home/mblasz/mimiker-sched0/include/sys/types.h \
  /home/mblasz/mimiker-sched0/include/endian.h \
  /home/mblasz/mimiker-sched0/include/sys/endian.h \
  /home/mblasz/mimiker-sched0/include/stddef.h \
  /home/mblasz/mimiker-sched0/include/stdint.h \
  /home/mblasz/mimiker-sched0/include/machine/int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/machine/int_const.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_const.h \
  /home/mblasz/mimiker-sched0/include/machine/types.h \
  /home/mblasz/mimiker-sched0/include/_locale.h \
  /home/mblasz/mimiker-sched0/include/stdlib.h \
  /home/mblasz/mimiker-sched0/include/wchar.h \
  /home/mblasz/mimiker-sched0/include/_wint.h \
  /home/mblasz/mimiker-sched0/lib/libc/include/reentrant.h \
  /home/mblasz/mimiker-sched0/include/signal.h \
  /home/mblasz/mimiker-sched0/include/sys/signal.h \
  /home/mblasz/mimiker-sched0/include/sys/sigtypes.h \
  /home/mblasz/mimiker-sched0/include/sys/siginfo.h stdio/local.h \
  stdio/wcio.h stdio/fileext.h \
  /home/mblasz/mimiker-sched0/include/limits.h \
  /home/mblasz/mimiker-sched0/include/sys/syslimits.h \
  /home/mblasz/mimiker-sched0/include/machine/limits.h \
  /home/mblasz/mimiker-sched0/include/_limits.h \
  /home/mblasz/mimiker-sched0/include/stdarg.h \
  /home/mblasz/mimiker-sched0/include/stdbool.h
