stdio/putwchar.o: stdio/putwchar.c \
  /home/mblasz/mimiker-sched0/include/sys/cdefs.h \
  /home/mblasz/mimiker-sched0/include/stdio.h \
  /home/mblasz/mimiker-sched0/include/sys/types.h \
  /home/mblasz/mimiker-sched0/include/endian.h \
  /home/mblasz/mimiker-sched0/include/sys/endian.h \
  /home/mblasz/mimiker-sched0/include/stddef.h \
  /home/mblasz/mimiker-sched0/include/stdint.h \
  /home/mblasz/mimiker-sched0/include/machine/int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/machine/int_const.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_const.h \
  /home/mblasz/mimiker-sched0/include/machine/types.h \
  /home/mblasz/mimiker-sched0/include/_locale.h \
  /home/mblasz/mimiker-sched0/include/wchar.h \
  /home/mblasz/mimiker-sched0/include/_wint.h
