# vim: tabstop=8 shiftwidth=8 noexpandtab:

TOPDIR = $(realpath ..)

SUBDIR = \
	 cmp \
	 col \
	 cut \
	 env \
	 find \
	 grep \
	 head \
	 id \
	 join \
	 login \
	 mkfifo \
	 stat \
	 seq \
	 tail \
	 tr \
	 uniq \
	 wc \
	 su

all: build

include $(TOPDIR)/build/common.mk
