# vim: tabstop=8 shiftwidth=8 noexpandtab:

TOPDIR = $(realpath ../../..)

CPPFLAGS += -I$(TOPDIR)/lib/libc/quad

SRCDIR = $(TOPDIR)/lib/libc/quad

SOURCES = qdivrem.c umoddi3.c udivdi3.c

include $(TOPDIR)/build/build.kern.mk
