# vim: tabstop=8 shiftwidth=8 noexpandtab list:

TOPDIR = $(realpath ..)

TARGET = mipsel-mimiker-elf

GCC_EXTRA_CONF = --with-arch=mips32r2 \
		 --with-abi=32 \
		 --with-float=hard

include $(TOPDIR)/target.mk
