TOPDIR = $(realpath ../..)

PROGRAM = su
SOURCES = su.c suutil.c
FORMAT-EXCLUDE = $(SOURCES)

LDLIBS = -lutil

#CPPFLAGS += -DALLOW_GROUP_CHANGE -DALLOW_EMPTY_USER

include $(TOPDIR)/build/build.prog.mk
