locale/fix_grouping.o: locale/fix_grouping.c \
  /home/mblasz/mimiker-sched0/include/sys/cdefs.h \
  /home/mblasz/mimiker-sched0/include/limits.h \
  /home/mblasz/mimiker-sched0/include/sys/syslimits.h \
  /home/mblasz/mimiker-sched0/include/machine/limits.h \
  /home/mblasz/mimiker-sched0/include/_limits.h \
  /home/mblasz/mimiker-sched0/include/stddef.h \
  /home/mblasz/mimiker-sched0/lib/libc/locale/fix_grouping.h
