TOPDIR = $(realpath ../..)

UELF_NAME = utest

SOURCES_C = \
	access.c \
	exceptions.c \
	fd.c \
	fork.c \
	lseek.c \
	main.c \
	misbehave.c \
	mmap.c \
	sbrk.c \
	signal.c \
	stat.c

include $(TOPDIR)/build/build.prog.mk
