# This file is a fork of GitHub Wiki Action plugin
# https://github.com/Andrew-Chen-Wang/github-wiki-action

name: GitHub Wiki Action
author: Andrew Chen Wang <acwangpython@gmail.com>

description: This action publishes Wiki pages from a provided directory into a GitHub repository's Wiki.
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  GH_TOKEN:
    description: 'The GitHub Token for this action to use. Specify secrets.GITHUB_TOKEN.'
    required: true
  GH_MAIL:
    description: 'The email associated with the token.'
    required: true
  GH_NAME:
    description: 'The username associated with the token.'
    required: true


