# vim: tabstop=8 shiftwidth=8 noexpandtab:

TOPDIR = $(realpath ../..)

SOURCES = efun.c login_tty.c logwtmp.c parsedate.y pty.c strpct.c \
	  raise_default_signal.c
FORMAT-EXCLUDE = %.c

include $(TOPDIR)/build/build.lib.mk
