# vim: tabstop=8 shiftwidth=8 noexpandtab list:

TOPDIR = $(realpath ..)

ARCH = amd64
TARGET = x86_64-mimiker-elf

GCC_EXTRA_CONF = --with-arch=x86-64 \
		 --with-abi=m64

include $(TOPDIR)/target.mk
