# vim: tabstop=8 shiftwidth=8 noexpandtab:

TOPDIR = $(realpath ../../..)

CPPFLAGS += -I$(CURDIR)

SOURCES = \
	fdt.c \
	fdt_addresses.c \
	fdt_empty_tree.c \
	fdt_overlay.c \
	fdt_ro.c \
	fdt_rw.c \
	fdt_strerror.c \
	fdt_sw.c \
	fdt_wip.c

include $(TOPDIR)/build/build.kern.mk
