#ifndef _MIPS_KCSAN_H_
#define _MIPS_KCSAN_H_

#define WATCHPOINT_READ_BIT (1L << 31)
#define WATCHPOINT_SIZE_SHIFT 29
#define WATCHPOINT_SIZE_MASK (~(WATCHPOINT_ADDR_MASK | WATCHPOINT_READ_BIT))
#define WATCHPOINT_ADDR_MASK ((1L << WATCHPOINT_SIZE_SHIFT) - 1)

#endif /* !_MIPS_KCSAN_H_ */
