ringbuf.o: ringbuf.c /home/mblasz/mimiker-sched0/include/sys/klog.h \
  /home/mblasz/mimiker-sched0/include/sys/types.h \
  /home/mblasz/mimiker-sched0/include/sys/cdefs.h \
  /home/mblasz/mimiker-sched0/include/endian.h \
  /home/mblasz/mimiker-sched0/include/sys/endian.h \
  /home/mblasz/mimiker-sched0/include/stddef.h \
  /home/mblasz/mimiker-sched0/include/stdint.h \
  /home/mblasz/mimiker-sched0/include/machine/int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/machine/int_const.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_const.h \
  /home/mblasz/mimiker-sched0/include/machine/types.h \
  /home/mblasz/mimiker-sched0/include/sys/ringbuf.h \
  /home/mblasz/mimiker-sched0/include/stdbool.h \
  /home/mblasz/mimiker-sched0/include/sys/uio.h \
  /home/mblasz/mimiker-sched0/include/sys/vm.h \
  /home/mblasz/mimiker-sched0/include/sys/queue.h \
  /home/mblasz/mimiker-sched0/include/machine/vm_param.h
