#include <sys/devclass.h>
#include <sys/emmc.h>

/* DEVCLASS_CREATE(emmc); */

static emmc_resp_type_t emmc_resp_types[57] = {
  [EMMC_CMD_GO_IDLE] = EMMCRESP_NONE,
  [EMMC_CMD_SEND_OP_COND] = EMMCRESP_R3,
  [EMMC_CMD_ALL_SEND_CID] = EMMCRESP_R2,
  [EMMC_CMD_SET_RELATIVE_ADDR] = EMMCRESP_R1,
  [EMMC_CMD_SET_DSR] = EMMCRESP_NONE,
  [EMMC_CMD_SLEEP_AWAKE] = EMMCRESP_R1,
  [EMMC_CMD_SWITCH] = EMMCRESP_R1,
  [EMMC_CMD_SELECT_CARD] = EMMCRESP_R1,
  [EMMC_CMD_SEND_EXT_CSD] = EMMCRESP_R1,
  [EMMC_CMD_SEND_CSD] = EMMCRESP_R2,
  [EMMC_CMD_SEND_CID] = EMMCRESP_R2,
  [EMMC_CMD_READ_DAT_UNTIL_STOP] = EMMCRESP_R1,
  [EMMC_CMD_STOP_TRANSMISSION] = EMMCRESP_R1,
  [EMMC_CMD_SEND_STATUS] = EMMCRESP_R1,
  [EMMC_CMD_BUSTEST_R] = EMMCRESP_R1,
  [EMMC_CMD_GO_INACTIVE_STATE] = EMMCRESP_NONE,
  [EMMC_CMD_BUSTEST_W] = EMMCRESP_R1,
  [EMMC_CMD_SET_BLOCKLEN] = EMMCRESP_R1,
  [EMMC_CMD_READ_BLOCK] = EMMCRESP_R1,
  [EMMC_CMD_READ_MULTIPLE_BLOCKS] = EMMCRESP_R1,
  [EMMC_CMD_WRITE_DAT_UNTIL_STOP] = EMMCRESP_R1,
  [EMMC_CMD_SET_BLOCK_COUNT] = EMMCRESP_R1,
  [EMMC_CMD_WRITE_BLOCK] = EMMCRESP_R1,
  [EMMC_CMD_WRITE_MULTIPLE_BLOCKS] = EMMCRESP_R1,
  [EMMC_CMD_PROGRAM_CID] = EMMCRESP_R1,
  [EMMC_CMD_PROGRAM_CSD] = EMMCRESP_R1,
  [EMMC_CMD_SET_WRITE_PROT] = EMMCRESP_R1,
  [EMMC_CMD_CLR_WRITE_PROT] = EMMCRESP_R1,
  [EMMC_CMD_SEND_WRITE_PROT] = EMMCRESP_R1,
  [EMMC_CMD_SEND_WRITE_PROT_TYPE] = EMMCRESP_R1,
  [EMMC_CMD_ERASE_GROUP_START] = EMMCRESP_R1,
  [EMMC_CMD_ERASE_GROUP_END] = EMMCRESP_R1,
  [EMMC_CMD_ERASE] = EMMCRESP_R1,
  [EMMC_CMD_FAST_IO] = EMMCRESP_R4,
  [EMMC_CMD_GO_IRQ_STATE] = EMMCRESP_R5,
  [EMMC_CMD_LOCK_UNLOCK] = EMMCRESP_R1,
  [EMMC_CMD_APP_CMD] = EMMCRESP_R1,
  [EMMC_CMD_GEN_CMD] = EMMCRESP_R1,
};

emmc_resp_type_t emmc_get_resp_type(emmc_command_t cmd) {
  return emmc_resp_types[(int)cmd];
}