/*
 * System call switch table.
 *
 * DO NOT EDIT: this file is automatically generated.
 * created from; Mimiker system call name/number "master" file.
 */

struct sysent sysent[] = {
  [SYS_syscall] = { sys_syscall },
  [SYS_exit] = { sys_exit },
  [SYS_fork] = { sys_fork },
  [SYS_read] = { sys_read },
  [SYS_write] = { sys_write },
  [SYS_open] = { sys_open },
  [SYS_close] = { sys_close },
  [SYS_lseek] = { sys_lseek },
  [SYS_unlink] = { sys_unlink },
  [SYS_getpid] = { sys_getpid },
  [SYS_kill] = { sys_kill },
  [SYS_fstat] = { sys_fstat },
  [SYS_sbrk] = { sys_sbrk },
  [SYS_mmap] = { sys_mmap },
  [SYS_mount] = { sys_mount },
  [SYS_getdirentries] = { sys_getdirentries },
  [SYS_dup] = { sys_dup },
  [SYS_dup2] = { sys_dup2 },
  [SYS_sigaction] = { sys_sigaction },
  [SYS_sigreturn] = { sys_sigreturn },
  [SYS_waitpid] = { sys_waitpid },
  [SYS_mkdir] = { sys_mkdir },
  [SYS_rmdir] = { sys_rmdir },
  [SYS_access] = { sys_access },
  [SYS_stat] = { sys_stat },
  [SYS_pipe] = { sys_pipe },
  [SYS_clock_gettime] = { sys_clock_gettime },
  [SYS_clock_nanosleep] = { sys_clock_nanosleep },
  [SYS_execve] = { sys_execve },
  [SYS_getppid] = { sys_getppid },
  [SYS_setpgid] = { sys_setpgid },
  [SYS_getpgid] = { sys_getpgid },
  [SYS_killpg] = { sys_killpg },
  [SYS_munmap] = { sys_munmap },
  [SYS_mprotect] = { sys_mprotect },
  [SYS_chdir] = { sys_chdir },
  [SYS_getcwd] = { sys_getcwd },
};

