# vim: tabstop=8 shiftwidth=8 noexpandtab list:

TOPDIR = $(realpath ..)

ARCH = aarch64
TARGET = aarch64-mimiker-elf

GCC_EXTRA_CONF = --with-arch=armv8-a \
		 --with-cpu=cortex-a53

include $(TOPDIR)/target.mk
