# vim: tabstop=8 shiftwidth=8 noexpandtab list:

TOPDIR = $(realpath ..)

ARCH = riscv32
TARGET = riscv32-mimiker-elf

GCC_EXTRA_CONF = --with-arch=rv32imaf \
		 --with-abi=ilp32f

include $(TOPDIR)/target.mk
