# vim: tabstop=8 shiftwidth=8 noexpandtab:

TOPDIR = $(realpath ../../..)

SOURCES = ctype_.c \
	  tolower_.c \
	  toupper_.c

include $(TOPDIR)/build/build.kern.mk

CPPFLAGS += -I$(CURDIR)/../include
