stdlib/strtoi.o: stdlib/strtoi.c \
  /home/mblasz/mimiker-sched0/include/sys/cdefs.h \
  /home/mblasz/mimiker-sched0/include/stddef.h \
  /home/mblasz/mimiker-sched0/include/assert.h \
  /home/mblasz/mimiker-sched0/include/errno.h \
  /home/mblasz/mimiker-sched0/include/sys/errno.h \
  /home/mblasz/mimiker-sched0/include/inttypes.h \
  /home/mblasz/mimiker-sched0/include/stdint.h \
  /home/mblasz/mimiker-sched0/include/machine/int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_mwgwtypes.h \
  /home/mblasz/mimiker-sched0/include/machine/int_const.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_const.h \
  /home/mblasz/mimiker-sched0/include/sys/inttypes.h \
  /home/mblasz/mimiker-sched0/include/machine/int_fmtio.h \
  /home/mblasz/mimiker-sched0/include/sys/common_int_fmtio.h \
  /home/mblasz/mimiker-sched0/include/_locale.h \
  /home/mblasz/mimiker-sched0/lib/libc/stdlib/_strtoi.h \
  /home/mblasz/mimiker-sched0/include/locale.h \
  /home/mblasz/mimiker-sched0/lib/libc/locale/setlocale_local.h \
  /home/mblasz/mimiker-sched0/include/sys/queue.h \
  /home/mblasz/mimiker-sched0/lib/libc/gen/ctype_local.h \
  /home/mblasz/mimiker-sched0/include/limits.h \
  /home/mblasz/mimiker-sched0/include/sys/syslimits.h \
  /home/mblasz/mimiker-sched0/include/machine/limits.h \
  /home/mblasz/mimiker-sched0/include/_limits.h
