# vim: tabstop=8 shiftwidth=8 noexpandtab:

TOPDIR = $(realpath ../../..)

SOURCES = strtol.c \
	  strtoul.c \
	  qsort.c \
	  rand.c

include $(TOPDIR)/build/build.kern.mk

CPPFLAGS += -I$(CURDIR)/../include

