#ifndef _AARCH64_KCSAN_H_
#define _AARCH64_KCSAN_H_

#define WATCHPOINT_READ_BIT (1L << 63)
#define WATCHPOINT_SIZE_SHIFT 61
#define WATCHPOINT_SIZE_MASK (~(WATCHPOINT_ADDR_MASK | WATCHPOINT_READ_BIT))
#define WATCHPOINT_ADDR_MASK ((1L << WATCHPOINT_SIZE_SHIFT) - 1)

#endif /* !_AARCH64_KCSAN_H_ */
