/*
 * System call numbers.
 *
 * DO NOT EDIT: this file is automatically generated.
 * created from; Mimiker system call name/number "master" file.
 */

#define SYS_syscall 0
#define SYS_exit 1
#define SYS_fork 2
#define SYS_read 3
#define SYS_write 4
#define SYS_openat 5
#define SYS_close 6
#define SYS_lseek 7
#define SYS_unlinkat 8
#define SYS_getpid 9
#define SYS_kill 10
#define SYS_fstat 11
#define SYS_sbrk 12
#define SYS_mmap 13
#define SYS_mount 14
#define SYS_getdents 15
#define SYS_dup 16
#define SYS_dup2 17
#define SYS_sigaction 18
#define SYS_sigreturn 19
#define SYS_wait4 20
#define SYS_mkdirat 21
#define SYS_symlinkat 22
#define SYS_faccessat 23
#define SYS_fstatat 24
#define SYS_pipe2 25
#define SYS_clock_gettime 26
#define SYS_clock_nanosleep 27
#define SYS_execve 28
#define SYS_getppid 29
#define SYS_setpgid 30
#define SYS_getpgid 31
#define SYS_umask 32
#define SYS_munmap 33
#define SYS_mprotect 34
#define SYS_chdir 35
#define SYS_getcwd 36
#define SYS_sigaltstack 37
#define SYS_sigprocmask 38
#define SYS_setcontext 39
#define SYS_ioctl 40
#define SYS_getresuid 41
#define SYS_getresgid 42
#define SYS_setresuid 43
#define SYS_setresgid 44
#define SYS_issetugid 45
#define SYS_fcntl 46
#define SYS_truncate 47
#define SYS_ftruncate 48
#define SYS_readlinkat 49
#define SYS_fchdir 50
#define SYS_linkat 51
#define SYS_fchmod 52
#define SYS_fchmodat 53
#define SYS_sched_yield 54
#define SYS_sigsuspend 55
#define SYS_setsid 56
#define SYS_getsid 57
#define SYS_MAXSYSCALL 58

#define SYS_MAXSYSARGS 6
